apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-react-app
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app 
    spec:
      containers:
      - name: react-app
        image: leon0408/react-app:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80